# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Response-streaming.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Response-streaming.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x18Response-streaming.proto\"\x18\n\x06number\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x18\n\x06square\x12\x0e\n\x06square\x18\x01 \x01(\x05\x32%\n\x02rs\x12\x1f\n\x07numbers\x12\x07.number\x1a\x07.square\"\x00\x30\x01')
)




_NUMBER = _descriptor.Descriptor(
  name='number',
  full_name='number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='number.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=52,
)


_SQUARE = _descriptor.Descriptor(
  name='square',
  full_name='square',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='square', full_name='square.square', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['number'] = _NUMBER
DESCRIPTOR.message_types_by_name['square'] = _SQUARE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

number = _reflection.GeneratedProtocolMessageType('number', (_message.Message,), dict(
  DESCRIPTOR = _NUMBER,
  __module__ = 'Response_streaming_pb2'
  # @@protoc_insertion_point(class_scope:number)
  ))
_sym_db.RegisterMessage(number)

square = _reflection.GeneratedProtocolMessageType('square', (_message.Message,), dict(
  DESCRIPTOR = _SQUARE,
  __module__ = 'Response_streaming_pb2'
  # @@protoc_insertion_point(class_scope:square)
  ))
_sym_db.RegisterMessage(square)



_RS = _descriptor.ServiceDescriptor(
  name='rs',
  full_name='rs',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=80,
  serialized_end=117,
  methods=[
  _descriptor.MethodDescriptor(
    name='numbers',
    full_name='rs.numbers',
    index=0,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_SQUARE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RS)

DESCRIPTOR.services_by_name['rs'] = _RS

# @@protoc_insertion_point(module_scope)
